name: Deploy

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: general
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set repository name variable
        run: echo "REPO_NAME=$(basename $GITHUB_REPOSITORY | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build Docker image
        run: DOCKER_BUILDKIT=0 docker build . -t localzet-${{ env.REPO_NAME }}:latest
